import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Navigation from './Navigation'

export default function Home() {
  return (
    <>
    <Navigation /> {/*Setter den utenfor container så den ikke skal være sentrert */}
    <div className={styles.container}>
      <Head>
        <title>Narcos mexico karakterer</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Oppgave 9
        </h1>

        <p className={styles.description}>
          Netflix lanserer en ny sesong av sin hit-show Narcos Mexico. Sesong 3 kommer ut
          5. november og jeg vil lage en introduksjon til alle karakterene fra serien for å holde
          deg oppdatert for nyeste sesongen :)
        </p>

        <div className={styles.grid}>
          {/* Knapp for å navigere til liste med karakterer */}
        </div>
      </main>
    </div>
    </>
  )
}
